


/* SQL TRANSFORMACION SEDES */

SELECT DISTINCT
PROGRAM_CAMPUS AS nombre_sede
FROM 
[dbo].[BAN_PROGRAM]


/* SQL TRANSFORMACION CARRERAS */
SELECT 
PROGRAM_CODE AS id_carrera, 
PROGRAM_LEGAL AS nombre_carrera,
PROGRAM_FACULTY 
FROM 
[dbo].[BAN_PROGRAM]


/* SQL TRANSFORMACION FACULTAD ESCUELA */
SELECT DISTINCT
PROGRAM_FACULTY AS nombre_fe
FROM [dbo].[BAN_PROGRAM]



/* SQL TRANSFORMACION ASIGNATURAS */
SELECT DISTINCT
b.MALLA_MATERIACURSO AS id_asignatura,
c.MALLA_ASIGNATURA AS nombre_asignatura,
c.MALLA_DEPTO_DESC AS asignatura_dpto,
MIN(c.MALLA_SEMESTRE) AS semestre_asignatura
FROM dbo.BAN_MALLA b
INNER JOIN BAN_MALLA c ON b.MALLA_MATERIACURSO = c.MALLA_MATERIACURSO
WHERE c.MALLA_CTLG = '201310' OR c.MALLA_CTLG = '202210' 
GROUP BY 
    b.MALLA_MATERIACURSO, 
    c.MALLA_ASIGNATURA,
    c.MALLA_DEPTO_DESC
ORDER BY b.MALLA_MATERIACURSO;


/* SQL TRANSFORMACION ASIGNATURAS_EST */
SELECT
a.HISTORIA_MATERIACURSO AS id_asignatura, 
a.HISTORIA_PERIODO AS periodo,
a.HISTORIA_PIDM AS pidm,
a.HISTORIA_CALIFICACION AS calificacion,
d.MALLA_CREDITAJE AS creditos
FROM dbo.BAN_HISTORIA a
INNER JOIN (SELECT DISTINCT
b.MALLA_MATERIACURSO,
b.MALLA_CREDITAJE
FROM dbo.BAN_MALLA b
INNER JOIN BAN_MALLA c 
ON b.MALLA_MATERIACURSO = c.MALLA_MATERIACURSO
WHERE c.MALLA_CTLG = '201310' OR c.MALLA_CTLG = '202210'
) d 
ON a.HISTORIA_MATERIACURSO = d.MALLA_MATERIACURSO
UNION
SELECT
	e.INSCRIPCION_MATERIACURSO,
	e.INSCRIPCION_PERIODO,
	e.INSCRIPCION_PIDM,
	NULL AS calificacion,
	z.MALLA_CREDITAJE
FROM 
	dbo.BAN_INSCRIPCION e
INNER JOIN dbo.BAN_MALLA z ON e.INSCRIPCION_MATERIACURSO = z.MALLA_MATERIACURSO;


/* SQL TRANSFORMACION ESTUDIANTES */

    /* DESDE BAN_USER */
    SELECT
    USER_PIDM AS pidm,
    USER_RUT AS rut_est, 
    USER_LEGAL_NOMBRE +' '+ USER_LEGAL_SEG_NOMBRE AS nombres_est,
    USER_LEGAL_APELLIDOS AS apellidos_est,
    USER_SEXO AS sexo_est,
    USER_COMUNA AS comuna_est,
    USER_NACIONALIDAD AS nacionalidad_est,
    USER_ETNIA AS etnia_est
    FROM
    [dbo].[BAN_USER]

    /* DESDE BAN_ADMISION */
    SELECT
    ADMISION_PERIODO AS cohorte_est, 
    ADMISION_INGRESO AS tipo_ingreso,
    ADMISION_PIDM AS pidm_a,
    ADMISION_CARRERA AS id_carrera
    FROM
    [dbo].[BAN_ADMISION]

/* SQL TRANSFORMACION MATRICULAS */

SELECT DISTINCT 
    DAI.dbo.BAN_ESTADOS_ACADEMICOS.RUT,
    EXITOACADEMICO.dbo.BAN_ADMISION.ADMISION_PIDM,
    DAI.dbo.BAN_ESTADOS_ACADEMICOS.NOMBRE,
    DAI.dbo.BAN_ESTADOS_ACADEMICOS.PERIODO,
    DAI.dbo.BAN_ESTADOS_ACADEMICOS.COD_PROGRAMA AS cod_programa,
    DAI.dbo.BAN_ESTADOS_ACADEMICOS.COD_ESTADO AS cod_estado,
    DAI.dbo.BAN_ESTADOS_ACADEMICOS.NOMBRE_ESTADO AS nombre_estado,
    DAI.dbo.BAN_ESTADOS_ACADEMICOS.FECHA_ESTADO AS fecha_estado
FROM 
    DAI.dbo.BAN_ESTADOS_ACADEMICOS 
INNER JOIN 
    EXITOACADEMICO.dbo.BAN_ADMISION 
    ON DAI.dbo.BAN_ESTADOS_ACADEMICOS.RUT COLLATE Latin1_General_100_CI_AI = EXITOACADEMICO.dbo.BAN_ADMISION.ADMISION_RUT COLLATE Latin1_General_100_CI_AI 
WHERE 
    DAI.dbo.BAN_ESTADOS_ACADEMICOS.COD_ESTADO IS NOT NULL 
    AND DAI.dbo.BAN_ESTADOS_ACADEMICOS.COD_ESTADO <> 'N'
    AND DAI.dbo.BAN_ESTADOS_ACADEMICOS.COD_ESTADO <> 'J'
   	AND DAI.dbo.BAN_ESTADOS_ACADEMICOS.COD_ESTADO <> 'D';




    