
CREATE SCHEMA dbo;

CREATE TABLE EXITOACADEMICO.dbo.BAN_ADMISION (
	ADMISION_PIDM numeric(6,0) NOT NULL,
	ADMISION_RUT varchar(9) COLLATE Modern_Spanish_CI_AS NOT NULL,
	ADMISION_PERIODO varchar(6) COLLATE Modern_Spanish_CI_AS NOT NULL,
	ADMISION_TIPOINGRESO varchar(8) COLLATE Modern_Spanish_CI_AS NOT NULL,
	ADMISION_INGRESO varchar(120) COLLATE Modern_Spanish_CI_AS NOT NULL,
	ADMISION_CARRERA varchar(48) COLLATE Modern_Spanish_CI_AS NOT NULL,
	ADMISION_PJPONDERADO varchar(81) COLLATE Modern_Spanish_CI_AS NULL,
	ADMISION_PJPNEM varchar(81) COLLATE Modern_Spanish_CI_AS NULL,
	ADMISION_PJPRANK varchar(81) COLLATE Modern_Spanish_CI_AS NULL,
	ADMISION_PJCIENCIAS varchar(81) COLLATE Modern_Spanish_CI_AS NULL,
	ADMISION_PJHISTORIA varchar(81) COLLATE Modern_Spanish_CI_AS NULL,
	ADMISION_PJLENGUAJE varchar(81) COLLATE Modern_Spanish_CI_AS NULL,
	ADMISION_PJMATEMATICAS varchar(81) COLLATE Modern_Spanish_CI_AS NULL,
	ADMISION_PJPROMLM varchar(81) COLLATE Modern_Spanish_CI_AS NULL,
	ADMISION_COLEGIO varchar(120) COLLATE Modern_Spanish_CI_AS NULL,
	ADMISION_RAMA varchar(4000) COLLATE Modern_Spanish_CI_AS NULL,
	ADMISION_DEPENDENCIA varchar(4000) COLLATE Modern_Spanish_CI_AS NULL,
	ADMISION_CUT varchar(20) COLLATE Modern_Spanish_CI_AS NULL,
	ADMISION_COMUNA varchar(120) COLLATE Modern_Spanish_CI_AS NULL,
	ADMISION_SYNC_DATE date NOT NULL
);


CREATE TABLE EXITOACADEMICO.dbo.BAN_BENEFICIO (
	BENEFICIO_PIDM numeric(6,0) NOT NULL,
	BENEFICIO_PERIODO varchar(6) COLLATE Modern_Spanish_CI_AS NOT NULL,
	BENEFICIO_CODE varchar(40) COLLATE Modern_Spanish_CI_AS NOT NULL,
	BENEFICIO_DESC varchar(320) COLLATE Modern_Spanish_CI_AS NOT NULL,
	BENEFICIO_LEGAL varchar(4000) COLLATE Modern_Spanish_CI_AS NULL,
	BENEFICIO_ACTIVITY_DATE date NOT NULL,
	BENEFICIO_SYNC_DATE date NOT NULL
);


CREATE TABLE EXITOACADEMICO.dbo.BAN_HISTORIA (
	HISTORIA_PIDM numeric(6,0) NOT NULL,
	HISTORIA_PERIODO varchar(6) COLLATE Modern_Spanish_CI_AS NOT NULL,
	HISTORIA_NRC varchar(5) COLLATE Modern_Spanish_CI_AS NULL,
	HISTORIA_MATERIACURSO varchar(9) COLLATE Modern_Spanish_CI_AS NOT NULL,
	HISTORIA_CALIFICACION varchar(6) COLLATE Modern_Spanish_CI_AS NOT NULL,
	HISTORIA_RECTIFICACION varchar(2) COLLATE Modern_Spanish_CI_AS NULL,
	HISTORIA_DESC varchar(200) COLLATE Modern_Spanish_CI_AS NULL,
	HISTORIA_ESTADO varchar(8) COLLATE Modern_Spanish_CI_AS NULL,
	HISTORIA_ACTIVITY_DATE date NOT NULL,
	HISTORIA_SYNC_DATE date NOT NULL
);


CREATE TABLE EXITOACADEMICO.dbo.BAN_INSCRIPCION (
	INSCRIPCION_PERIODO varchar(6) COLLATE Modern_Spanish_CI_AS NOT NULL,
	INSCRIPCION_PIDM numeric(6,0) NOT NULL,
	INSCRIPCION_MATERIACURSO varchar(9) COLLATE Modern_Spanish_CI_AS NOT NULL,
	INSCRIPCION_ESTADO varchar(10) COLLATE Modern_Spanish_CI_AS NOT NULL,
	INSCRIPCION_ACTIVITY_DATE date NOT NULL,
	INSCRIPCION_SYNC_DATE date NOT NULL
);



CREATE TABLE EXITOACADEMICO.dbo.BAN_MALLA (
	MALLA_PROGRAM_CODE varchar(4) COLLATE Modern_Spanish_CI_AS NOT NULL,
	MALLA_AREA varchar(40) COLLATE Modern_Spanish_CI_AS NOT NULL,
	MALLA_SEMESTRE varchar(120) COLLATE Modern_Spanish_CI_AS NULL,
	MALLA_CTLG varchar(24) COLLATE Modern_Spanish_CI_AS NOT NULL,
	MALLA_FORMACION varchar(40) COLLATE Modern_Spanish_CI_AS NULL,
	MALLA_MATERIACURSO varchar(36) COLLATE Modern_Spanish_CI_AS NOT NULL,
	MALLA_CREDITAJE numeric(7,3) NOT NULL,
	MALLA_ASIGNATURA varchar(120) COLLATE Modern_Spanish_CI_AS NOT NULL,
	MALLA_DEPTO varchar(16) COLLATE Modern_Spanish_CI_AS NOT NULL,
	MALLA_DEPTO_DESC varchar(120) COLLATE Modern_Spanish_CI_AS NOT NULL,
	MALLA_AREA_ACTIVITY_DATE date NOT NULL,
	MALLA_ASIG_ACTIVITY_DATE date NOT NULL,
	MALLA_SYNC_DATE date NOT NULL
);



CREATE TABLE EXITOACADEMICO.dbo.BAN_PLAN_ESTUDIO (
	PLAN_PIDM numeric(6,0) NOT NULL,
	PLAN_PERIODO varchar(6) COLLATE Modern_Spanish_CI_AS NOT NULL,
	PLAN_ADMISION varchar(6) COLLATE Modern_Spanish_CI_AS NOT NULL,
	PLAN_CODE varchar(2) COLLATE Modern_Spanish_CI_AS NOT NULL,
	PLAN_PROGRAM_CODE varchar(12) COLLATE Modern_Spanish_CI_AS NOT NULL,
	PLAN_ESTADO varchar(32) COLLATE Modern_Spanish_CI_AS NOT NULL,
	PLAN_ESTUDIO_PATH varchar(4000) COLLATE Modern_Spanish_CI_AS NULL,
	PLAN_CAMPUS varchar(11) COLLATE Modern_Spanish_CI_AS NOT NULL,
	PLAN_SYNC_DATE date NOT NULL
);



CREATE TABLE EXITOACADEMICO.dbo.BAN_PROGRAM (
	PROGRAM_CODE varchar(4) COLLATE Modern_Spanish_CI_AS NOT NULL,
	PROGRAM_DESC varchar(30) COLLATE Modern_Spanish_CI_AS NOT NULL,
	PROGRAM_LEGAL varchar(4000) COLLATE Modern_Spanish_CI_AS NULL,
	PROGRAM_FACULTY varchar(50) COLLATE Modern_Spanish_CI_AS NULL,--SE SUBIO A 50. 
	PROGRAM_LEVEL varchar(30) COLLATE Modern_Spanish_CI_AS NULL,
	PROGRAM_CAMPUS varchar(30) COLLATE Modern_Spanish_CI_AS NULL,
	PROGRAM_ACTIVITY_DATE date NOT NULL,
	PROGRAM_SYNC_DATE date NOT NULL
);



CREATE TABLE EXITOACADEMICO.dbo.BAN_USER (
	USER_PIDM numeric(6,0) NOT NULL,
	USER_RUT varchar(9) COLLATE Modern_Spanish_CI_AS NOT NULL,
	USER_LEGAL_NOMBRE varchar(240) COLLATE Modern_Spanish_CI_AS NOT NULL,
	USER_LEGAL_SEG_NOMBRE varchar(240) COLLATE Modern_Spanish_CI_AS NULL,
	USER_LEGAL_APELLIDOS varchar(240) COLLATE Modern_Spanish_CI_AS NOT NULL,
	USER_SOCIAL_NOMBRE varchar(240) COLLATE Modern_Spanish_CI_AS NULL,
	USER_SOCIAL_SEG_NOMBRE varchar(240) COLLATE Modern_Spanish_CI_AS NULL,
	USER_SOCIAL_APELLIDOS varchar(240) COLLATE Modern_Spanish_CI_AS NULL,
	USER_EMAIL varchar(512) COLLATE Modern_Spanish_CI_AS NULL,
	USER_SEXO varchar(13) COLLATE Modern_Spanish_CI_AS NOT NULL,
	USER_F_NACIMIENTO varchar(13) COLLATE Modern_Spanish_CI_AS NOT NULL,
	USER_ETNIA varchar(120) COLLATE Modern_Spanish_CI_AS NULL,
	USER_CUT varchar(20) COLLATE Modern_Spanish_CI_AS NULL,
	USER_COMUNA varchar(120) COLLATE Modern_Spanish_CI_AS NULL,
	USER_NACIONALIDAD varchar(4000) COLLATE Modern_Spanish_CI_AS NULL,
	USER_LEGAL_ACTIVITY_DATE date NULL,
	USER_SOCIAL_ACTIVITY_DATE date NULL,
	USER_EMAIL_ACTIVITY_DATE date NULL,
	USER_SYNC_DATE date NOT NULL
);

